### ISSUE TITLE
Change text in Save/Confirm Event

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#267]
Can we change the text instead of reading "SAVE EVENT" to read “SEND POLL” & “CONFIRM AND SEND INVITE”.

**Comment by sohilpandya** [comment]
@rickardinho can you please test this out, it should be fixed now. 

Please close if fixed.

Thanks

**Comment by rickardinho** [comment]
CREATE EVENT should read "CONFIRM & SEND INVITE"

**Comment by sohilpandya** [comment]
Hi @rickardinho could you please check again, we've got the correct text
![screen shot 2016-06-09 at 13 00 07](https://cloud.githubusercontent.com/assets/2305591/15929001/2de39b6e-2e42-11e6-818b-a6c759ce27f5.png)

**Comment by rickardinho** [comment]
I'm still getting the old text. See screenshot. This screen is after polling and selecting and confirming
![shot_2016-06-09_15-52-06](https://cloud.githubusercontent.com/assets/17908724/15934207/99a46f6e-2e5a-11e6-8ca3-de50a4b73cd7.png)
